version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: newsfeed
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9001:9000"
      - "9002:9001" # for MinIO console
    command: server /data --console-address ":9002"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  createbuckets:
    image: minio/minio
    depends_on:
      - minio
    links:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9001 admin 12345678; /usr/bin/mc mb myminio/images; /usr/bin/mc policy set public myminio/images; exit 0; "
    networks:
      - app-network
volumes:
  mysql_data:
  minio_data:


networks:
  app-network:
