version: "1.0"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    container_name: golang-redis
    image: redis:6.2.7
    ports:
      - 6379:6379

volumes:
  mysql-data:
